### ISSUE TITLE
Would a dependency solver available as a WebAssemby module be useful to you?

### ISSUE THREAD

**Issue by mpizenberg** [opvasger/develm#7]
I'm toying with the idea of extracting a webassembly module from the dependency resolver in elm-test-rs and making the wasm module available wrapped in an es module with the following function:

```js
// Returns the `elm.json` needed to run the tests
// with the dependencies solved.
//
// Inputs:
//   projectElmJson: the JSON string containing the `elm.json` file of the project.
//   fetchElmJson: a function able to retrieve the `elm.json` of a given package version.
//       fetchElmJson(author, package, version) -> string
//   listAvailableVersions: function returning the list of available versions of a package.
//       The order of the list implies the prioritazation of the versions that will be picked.
//       So to solve with newest versions, list the versions in reverse orders.
//       listAvailableVersions(author, package) -> [ string ]
function solveTestDeps(projectElmJson, fetchElmJson, listAvailableVersions)
```

This could happen relatively soon with the right motivation since creating a wasm module from Rust code is relatively easy, and definitely sooner than the rewrite of elm-pubgrub I need to do at some point. Could this be useful to you?

**Comment by opvasger** [comment]
I appreciate the offer, but I don't really know how complicated a problem this is, and I'd rather write some simple typescript to resolve dependencies, instead of relying on code I don't have the skill to maintain myself :sunny:

I'll chip away at the problem some more when I have the time, and let you know if I'll want your rust-implementation!

thanks again! :sunny:

**Comment by mpizenberg** [comment]
That's fair!

A warning, dependency solving is a really complex NP complete problem so it's hard to implement in an efficient way. When I started elm-test-rs, I didn't realize that I would have spent like 3 months on the first prototype, and 1 full year just to get dependency solving right. But that's because I got carried away and tried re-implementing state of the art algorithms (pubgrub).

But Elm dependencies are usually really small in general so you can get away with an exhaustive search and simple backtracking as that's what Evan does in the elm compiler for the time being.

**Comment by opvasger** [comment]
thanks for sharing - I'm going for something simple, but I'll definitely let you know if I realize I need something better than what I have in mind :sunny:
